//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::ThirdPersonController.MovementStateMachine.Features.Move.SprintFeature))]
	public class PropertyProvider_ThirdPersonController_MovementStateMachine_Features_Move_SprintFeature : Unity.VisualScripting.SerializedPropertyProvider<ThirdPersonController.MovementStateMachine.Features.Move.SprintFeature>
	{
	}
}
