//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MTPS.Shooter.FightingStateMachine.Features.Scope;

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::MTPS.Shooter.FightingStateMachine.Features.Scope.SetScopeActiveFeature))]
	public class PropertyProvider_SetScopeActiveFeature : Unity.VisualScripting.SerializedPropertyProvider<SetScopeActiveFeature>
	{
	}
}
