//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MTPS.Movement.Transitions;

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::MTPS.Movement.Transitions.CrouchStateTransition))]
	public class PropertyProvider_ThirdPersonController_MovementStateMachine_Code_Transitions_CrouchStateTransition : Unity.VisualScripting.SerializedPropertyProvider<CrouchStateTransition>
	{
	}
}
