//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MTPS.Movement.Features.AlwaysExecuted;

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::MTPS.Movement.Features.AlwaysExecuted.MovementSoundsFeature))]
	public class PropertyProvider_ThirdPersonController_MovementStateMachine_Features_MovementSoundsFeature : Unity.VisualScripting.SerializedPropertyProvider<MovementSoundsFeature>
	{
	}
}
